### ISSUE TITLE
Bug: Auckland does not combine with other locations using "and"

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/solvis-api#17]
When requesting ruptures though multiple locations Auckland combined with another location includes ruptures that do not intersect the Auckland radius. This does not appear to be the case for other combinations e.g. Wellington and Queenstown.

**Comment by chrisbc** [comment]
FYI @chrisdicaprio this PR fixes this bug

**Comment by chrisbc** [comment]
@chrisdicaprio can you close this if you agree it's now working correctly in ToshiUI ?
